# Site settings
title: Etü Bilir
email: etubilir@gmail.com
url: https://etubilir.github.io
description: "Erzurum Teknik Üniversitesi Bilim ve Fikir Kulübü Resmi Web Sitesi"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: etubilir.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/etubilir
    #  - title: facebook
    #url: https://facebook.com/etubilir
  - title: instagram
    url: http://instagram.com/etubilir
  - title: github
    url: https://github.com/etubilir

# Build settings
markdown: kramdown
permalink: pretty
